jobs:
  build:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./run/action

name: Ci

on:
  schedule:
    - cron: "50 2/3 * * *"
